# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qtya.core.v1 import mgmt_pb2 as qtya_dot_core_dot_v1_dot_mgmt__pb2


class ManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/qtya.core.v1.ManagementService/AddUser',
                request_serializer=qtya_dot_core_dot_v1_dot_mgmt__pb2.AddUserRequest.SerializeToString,
                response_deserializer=qtya_dot_core_dot_v1_dot_mgmt__pb2.AddUserResponse.FromString,
                )


class ManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=qtya_dot_core_dot_v1_dot_mgmt__pb2.AddUserRequest.FromString,
                    response_serializer=qtya_dot_core_dot_v1_dot_mgmt__pb2.AddUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qtya.core.v1.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.core.v1.ManagementService/AddUser',
            qtya_dot_core_dot_v1_dot_mgmt__pb2.AddUserRequest.SerializeToString,
            qtya_dot_core_dot_v1_dot_mgmt__pb2.AddUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
