# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qtya/core/v1/platformuser.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from qtya.core.v1 import prototime_pb2 as qtya_dot_core_dot_v1_dot_prototime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fqtya/core/v1/platformuser.proto\x12\x0cqtya.core.v1\x1a google/protobuf/descriptor.proto\x1a\x1cqtya/core/v1/prototime.proto\"\xd2\x01\n\x0cPlatformUser\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\x12\x14\n\x05token\x18\x04 \x01(\tR\x05token\x12:\n\x0cregistred_at\x18\x05 \x01(\x0b\x32\x17.qtya.core.v1.ProtoTimeR\x0bregistredAt\x12\x36\n\nlast_login\x18\x06 \x01(\x0b\x32\x17.qtya.core.v1.ProtoTimeR\tlastLoginB2Z0github.com/qtyapp/qtya_proto/qtya/core/v1;corev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qtya.core.v1.platformuser_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/qtyapp/qtya_proto/qtya/core/v1;corev1'
  _globals['_PLATFORMUSER']._serialized_start=114
  _globals['_PLATFORMUSER']._serialized_end=324
# @@protoc_insertion_point(module_scope)
