// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: rtc/rtc.proto

package rtc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RTCService_Signal_FullMethodName = "/rtc.RTCService/Signal"
)

// RTCServiceClient is the client API for RTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RTCServiceClient interface {
	Signal(ctx context.Context, opts ...grpc.CallOption) (RTCService_SignalClient, error)
}

type rTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRTCServiceClient(cc grpc.ClientConnInterface) RTCServiceClient {
	return &rTCServiceClient{cc}
}

func (c *rTCServiceClient) Signal(ctx context.Context, opts ...grpc.CallOption) (RTCService_SignalClient, error) {
	stream, err := c.cc.NewStream(ctx, &RTCService_ServiceDesc.Streams[0], RTCService_Signal_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &rTCServiceSignalClient{stream}
	return x, nil
}

type RTCService_SignalClient interface {
	Send(*Request) error
	Recv() (*Reply, error)
	grpc.ClientStream
}

type rTCServiceSignalClient struct {
	grpc.ClientStream
}

func (x *rTCServiceSignalClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rTCServiceSignalClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RTCServiceServer is the server API for RTCService service.
// All implementations must embed UnimplementedRTCServiceServer
// for forward compatibility
type RTCServiceServer interface {
	Signal(RTCService_SignalServer) error
	mustEmbedUnimplementedRTCServiceServer()
}

// UnimplementedRTCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRTCServiceServer struct {
}

func (UnimplementedRTCServiceServer) Signal(RTCService_SignalServer) error {
	return status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedRTCServiceServer) mustEmbedUnimplementedRTCServiceServer() {}

// UnsafeRTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RTCServiceServer will
// result in compilation errors.
type UnsafeRTCServiceServer interface {
	mustEmbedUnimplementedRTCServiceServer()
}

func RegisterRTCServiceServer(s grpc.ServiceRegistrar, srv RTCServiceServer) {
	s.RegisterService(&RTCService_ServiceDesc, srv)
}

func _RTCService_Signal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RTCServiceServer).Signal(&rTCServiceSignalServer{stream})
}

type RTCService_SignalServer interface {
	Send(*Reply) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type rTCServiceSignalServer struct {
	grpc.ServerStream
}

func (x *rTCServiceSignalServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rTCServiceSignalServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RTCService_ServiceDesc is the grpc.ServiceDesc for RTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtc.RTCService",
	HandlerType: (*RTCServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Signal",
			Handler:       _RTCService_Signal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rtc/rtc.proto",
}
