# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rtc import rtc_pb2 as rtc_dot_rtc__pb2


class RTCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Signal = channel.stream_stream(
                '/rtc.RTCService/Signal',
                request_serializer=rtc_dot_rtc__pb2.Request.SerializeToString,
                response_deserializer=rtc_dot_rtc__pb2.Reply.FromString,
                )


class RTCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Signal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RTCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Signal': grpc.stream_stream_rpc_method_handler(
                    servicer.Signal,
                    request_deserializer=rtc_dot_rtc__pb2.Request.FromString,
                    response_serializer=rtc_dot_rtc__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rtc.RTCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RTCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Signal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/rtc.RTCService/Signal',
            rtc_dot_rtc__pb2.Request.SerializeToString,
            rtc_dot_rtc__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
