# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qtya.chat.v1 import chat_pb2 as qtya_dot_chat_dot_v1_dot_chat__pb2


class ChatServiceStub(object):
    """ChatService is the chat service for the Qtya.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/qtya.chat.v1.ChatService/Register',
                request_serializer=qtya_dot_chat_dot_v1_dot_chat__pb2.RegisterRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v1_dot_chat__pb2.RegisterResponse.FromString,
                )
        self.EventStream = channel.stream_stream(
                '/qtya.chat.v1.ChatService/EventStream',
                request_serializer=qtya_dot_chat_dot_v1_dot_chat__pb2.EventStreamRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v1_dot_chat__pb2.EventStreamResponse.FromString,
                )


class ChatServiceServicer(object):
    """ChatService is the chat service for the Qtya.
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=qtya_dot_chat_dot_v1_dot_chat__pb2.RegisterRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v1_dot_chat__pb2.RegisterResponse.SerializeToString,
            ),
            'EventStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=qtya_dot_chat_dot_v1_dot_chat__pb2.EventStreamRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v1_dot_chat__pb2.EventStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qtya.chat.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """ChatService is the chat service for the Qtya.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v1.ChatService/Register',
            qtya_dot_chat_dot_v1_dot_chat__pb2.RegisterRequest.SerializeToString,
            qtya_dot_chat_dot_v1_dot_chat__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/qtya.chat.v1.ChatService/EventStream',
            qtya_dot_chat_dot_v1_dot_chat__pb2.EventStreamRequest.SerializeToString,
            qtya_dot_chat_dot_v1_dot_chat__pb2.EventStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
