# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qtya.chat.v2 import chatservice_pb2 as qtya_dot_chat_dot_v2_dot_chatservice__pb2


class ChatServiceStub(object):
    """ChatService is the chat service for the messenger.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/qtya.chat.v2.ChatService/Login',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.LoginRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.LoginResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/qtya.chat.v2.ChatService/SendMessage',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SendMessageResponse.FromString,
                )
        self.GetMessages = channel.unary_unary(
                '/qtya.chat.v2.ChatService/GetMessages',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetMessagesResponse.FromString,
                )
        self.GetConversations = channel.unary_unary(
                '/qtya.chat.v2.ChatService/GetConversations',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetConversationsRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetConversationsResponse.FromString,
                )
        self.CreateConversation = channel.unary_unary(
                '/qtya.chat.v2.ChatService/CreateConversation',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.CreateConversationRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.CreateConversationResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/qtya.chat.v2.ChatService/GetUser',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetUserRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetUserResponse.FromString,
                )
        self.SearchUsers = channel.unary_unary(
                '/qtya.chat.v2.ChatService/SearchUsers',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SearchUsersRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SearchUsersResponse.FromString,
                )
        self.MessageReaded = channel.unary_unary(
                '/qtya.chat.v2.ChatService/MessageReaded',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.MessageReadedRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.MessageReadedResponse.FromString,
                )
        self.UpdatePresence = channel.unary_unary(
                '/qtya.chat.v2.ChatService/UpdatePresence',
                request_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.UpdatePresenceRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.UpdatePresenceResponse.FromString,
                )


class ChatServiceServicer(object):
    """ChatService is the chat service for the messenger.
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MessageReaded(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePresence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.LoginRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.LoginResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SendMessageRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetMessagesRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetMessagesResponse.SerializeToString,
            ),
            'GetConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversations,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetConversationsRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetConversationsResponse.SerializeToString,
            ),
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.CreateConversationRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.CreateConversationResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetUserRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetUserResponse.SerializeToString,
            ),
            'SearchUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUsers,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SearchUsersRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.SearchUsersResponse.SerializeToString,
            ),
            'MessageReaded': grpc.unary_unary_rpc_method_handler(
                    servicer.MessageReaded,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.MessageReadedRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.MessageReadedResponse.SerializeToString,
            ),
            'UpdatePresence': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePresence,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.UpdatePresenceRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_chatservice__pb2.UpdatePresenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qtya.chat.v2.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """ChatService is the chat service for the messenger.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/Login',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.LoginRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/SendMessage',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.SendMessageRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.SendMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/GetMessages',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetMessagesRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/GetConversations',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetConversationsRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetConversationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/CreateConversation',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.CreateConversationRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.CreateConversationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/GetUser',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetUserRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/SearchUsers',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.SearchUsersRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.SearchUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MessageReaded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/MessageReaded',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.MessageReadedRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.MessageReadedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePresence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/qtya.chat.v2.ChatService/UpdatePresence',
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.UpdatePresenceRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_chatservice__pb2.UpdatePresenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
