# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qtya/chat/v2/realtime.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'qtya/chat/v2/realtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from qtya.core.v1 import prototime_pb2 as qtya_dot_core_dot_v1_dot_prototime__pb2
from qtya.chat.v2 import messages_pb2 as qtya_dot_chat_dot_v2_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bqtya/chat/v2/realtime.proto\x12\x0cqtya.chat.v2\x1a google/protobuf/descriptor.proto\x1a\x1cqtya/core/v1/prototime.proto\x1a\x1bqtya/chat/v2/messages.proto\"+\n\x13ListenEventsRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"\xf1\x06\n\x14ListenEventsResponse\x12W\n\x15\x63hat_message_received\x18\x01 \x01(\x0b\x32!.qtya.chat.v2.ChatMessageReceivedH\x00R\x13\x63hatMessageReceived\x12I\n\x0emessage_readed\x18\x02 \x01(\x0b\x32 .qtya.chat.v2.MessageReadedEventH\x00R\rmessageReaded\x12W\n\x15user_presence_changed\x18\x03 \x01(\x0b\x32!.qtya.chat.v2.UserPresenceChangedH\x00R\x13userPresenceChanged\x12V\n\x14\x63onversation_created\x18\x04 \x01(\x0b\x32!.qtya.chat.v2.ConversationCreatedH\x00R\x13\x63onversationCreated\x12V\n\x14\x63onversation_updated\x18\x05 \x01(\x0b\x32!.qtya.chat.v2.ConversationUpdatedH\x00R\x13\x63onversationUpdated\x12`\n\x18user_joined_conversation\x18\x06 \x01(\x0b\x32$.qtya.chat.v2.UserJoinedConversationH\x00R\x16userJoinedConversation\x12Z\n\x16user_left_conversation\x18\x07 \x01(\x0b\x32\".qtya.chat.v2.UserLeftConversationH\x00R\x14userLeftConversation\x12G\n\x0fmessage_deleted\x18\x08 \x01(\x0b\x32\x1c.qtya.chat.v2.MessageDeletedH\x00R\x0emessageDeleted\x12G\n\x0fmessage_updated\x18\t \x01(\x0b\x32\x1c.qtya.chat.v2.MessageUpdatedH\x00R\x0emessageUpdated\x12S\n\x13\x61ttachment_uploaded\x18\n \x01(\x0b\x32 .qtya.chat.v2.AttachmentUploadedH\x00R\x12\x61ttachmentUploadedB\x07\n\x05\x65vent2l\n\x0fRealtimeService\x12Y\n\x0cListenEvents\x12!.qtya.chat.v2.ListenEventsRequest\x1a\".qtya.chat.v2.ListenEventsResponse\"\x00\x30\x01\x42\x32Z0github.com/qtyapp/qtya_proto/qtya/chat/v2;chatv2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qtya.chat.v2.realtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/qtyapp/qtya_proto/qtya/chat/v2;chatv2'
  _globals['_LISTENEVENTSREQUEST']._serialized_start=138
  _globals['_LISTENEVENTSREQUEST']._serialized_end=181
  _globals['_LISTENEVENTSRESPONSE']._serialized_start=184
  _globals['_LISTENEVENTSRESPONSE']._serialized_end=1065
  _globals['_REALTIMESERVICE']._serialized_start=1067
  _globals['_REALTIMESERVICE']._serialized_end=1175
# @@protoc_insertion_point(module_scope)
