# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from qtya.chat.v2 import realtime_pb2 as qtya_dot_chat_dot_v2_dot_realtime__pb2


class RealtimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenEvents = channel.unary_stream(
                '/qtya.chat.v2.RealtimeService/ListenEvents',
                request_serializer=qtya_dot_chat_dot_v2_dot_realtime__pb2.ListenEventsRequest.SerializeToString,
                response_deserializer=qtya_dot_chat_dot_v2_dot_realtime__pb2.ListenEventsResponse.FromString,
                )


class RealtimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListenEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RealtimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenEvents,
                    request_deserializer=qtya_dot_chat_dot_v2_dot_realtime__pb2.ListenEventsRequest.FromString,
                    response_serializer=qtya_dot_chat_dot_v2_dot_realtime__pb2.ListenEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qtya.chat.v2.RealtimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RealtimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListenEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/qtya.chat.v2.RealtimeService/ListenEvents',
            qtya_dot_chat_dot_v2_dot_realtime__pb2.ListenEventsRequest.SerializeToString,
            qtya_dot_chat_dot_v2_dot_realtime__pb2.ListenEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
